config/routes.rb
Rails.application.routes.draw do
  resources :squabblers
  get 'pages/about'
  get 'pages/contact'

root 'squabblers#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/squabbler.rb
class Squabbler < ApplicationRecord
  has_attached_file :image, styles: { medium: "200x", thumb: "100x100>" }, default_url: "default.png"
validates_attachment_content_type :image, :content_type => ["image/jpg", "image/jpeg", "image/png", "image/gif"]
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def about
  end

  def contact
  end
end

app/controllers/squabblers_controller.rb
class SquabblersController < ApplicationController
  before_action :set_squabbler, only: [:show, :edit, :update, :destroy]

  # GET /squabblers
  # GET /squabblers.json
  def index
    @squabblers = Squabbler.all
  end

  # GET /squabblers/1
  # GET /squabblers/1.json
  def show
  end

  # GET /squabblers/new
  def new
    @squabbler = Squabbler.new
  end

  # GET /squabblers/1/edit
  def edit
  end

  # POST /squabblers
  # POST /squabblers.json
  def create
    @squabbler = Squabbler.new(squabbler_params)

    respond_to do |format|
      if @squabbler.save
        format.html { redirect_to @squabbler, notice: 'Squabbler was successfully created.' }
        format.json { render :show, status: :created, location: @squabbler }
      else
        format.html { render :new }
        format.json { render json: @squabbler.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /squabblers/1
  # PATCH/PUT /squabblers/1.json
  def update
    respond_to do |format|
      if @squabbler.update(squabbler_params)
        format.html { redirect_to @squabbler, notice: 'Squabbler was successfully updated.' }
        format.json { render :show, status: :ok, location: @squabbler }
      else
        format.html { render :edit }
        format.json { render json: @squabbler.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /squabblers/1
  # DELETE /squabblers/1.json
  def destroy
    @squabbler.destroy
    respond_to do |format|
      format.html { redirect_to squabblers_url, notice: 'Squabbler was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_squabbler
      @squabbler = Squabbler.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def squabbler_params
      params.require(:squabbler).permit(:fname, :lname, :alias, :sole_squabbler, :team_squabbler, :judge, :twitter_handle, :facebook, :age, :country, :gender, :image)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/squabblers_helper.rb
module SquabblersHelper
end

app/views/layouts/_footer.html.erb
<p>Copyright 2017</p>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
            <a class="navbar-brand" href="/squabblers#index">Squabbles</a>
      <a class="navbar-brand" href='/squabblers#index'>

        <!-- /.<img alt="S" src="s3.jpeg">-->
      </a>
    </div>
    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><a href="/pages/contact">contact</a></li>
        <li><a href="/pages/about">About</a></li>

      </ul>


    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Squabbles</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>



<%= render 'layouts/header' %>

<div class="container">
    <%= yield %>


<%= render 'layouts/footer' %>
</div>

  </body>
</html>

app/views/pages/about.html.erb
<h1>Welcome to Squabbles</h1>
<p>The place where you can argument with anyone</p>
<!-- /.Pill nav bar -->
    <ul class="nav nav-pills nav-stacked">
      <li role="presentation" class="active"><a href="/pages/about">About</a></li>
      <li role="presentation"><a href="/pages/contact">contact</a></li>
      <li role="presentation"><a href="/squabblers">Squabblers</a></li>
    </ul>

app/views/pages/contact.html.erb
<p>Find me in app/views/pages/contact.html.erb</p>

app/views/squabblers/_form.html.erb
<%= form_for(squabbler, html: { multipart: true } ) do |f| %>
  <% if squabbler.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(squabbler.errors.count, "error") %> prohibited this squabbler from being saved:</h2>

      <ul>
      <% squabbler.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :first_name %>
    <%= f.text_field :fname, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :last_name %>
    <%= f.text_field :lname, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :alias %>
    <%= f.text_field :alias, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :sole_squabbler %>
    <%= f.text_field :sole_squabbler, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :team_squabbler %>
    <%= f.text_field :team_squabbler, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :judge %>
    <%= f.text_field :judge, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :twitter_handle %>
    <%= f.text_field :twitter_handle, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :facebook %>
    <%= f.text_field :facebook, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :age %>
    <%= f.text_field :age, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :country %>
    <%= f.text_field :country, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :gender %>
    <%= f.text_field :gender, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :image %>
    <%= f.file_field :image, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.submit class: "btn btn-primary"%>
  </div>
<% end %>

app/views/squabblers/edit.html.erb
<h1>Editing Squabbler</h1>

<%= render 'form', squabbler: @squabbler %>

<%= link_to 'Show', @squabbler, class: "btn btn-link" %> |
<%= link_to 'Back', squabblers_path, class: "btn btn-link" %>

app/views/squabblers/index.html.erb
<p id="notice"><%= notice %></p>

<div class="center">
  <div class="row">
        <% @squabblers.each do |squabbler| %>
    <div class="col-md-4">
      <div class="thumbnail">
          <%= image_tag squabbler.image.url(:medium) %>
        <div class="caption">
          <h3><%= squabbler.fname %></h3>
          <p>  <%= squabbler.alias %></p>
          <p>
            <a href="#" class="btn btn-primary" role="button">Show</a>
            <a href="#" class="btn btn-default" role="button">Edit</a>
            <a href="#" class="btn btn-default" role="button">Destroy</a>
            <a href="#" class="btn btn-default" role="button">Show</a>
          </p>
          <%= link_to 'Show', squabbler, class: "btn btn-link" %><br>
          <%= link_to 'Edit', edit_squabbler_path(squabbler), class: "btn btn-link" %><br>
          <%= link_to 'Destroy', squabbler, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-link" %>
        </div>
      </div>
    </div>
  <% end %>
  </div>
</div>



<h1>Squabblers</h1>

<table>
  <thead>
    <tr>
      <th>Image</th>
      <th>Fname</th>
      <th>Lname</th>
      <th>Alias</th>
      <th>Sole squabbler</th>
      <th>Team squabbler</th>
      <th>Judge</th>
      <th>Twitter handle</th>
      <th>Facebook</th>
      <th>Age</th>
      <th>Country</th>
      <th>Gender</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @squabblers.each do |squabbler| %>
      <tr>
          <td><%= image_tag squabbler.image.url(:thumb) %></td>
        <td><%= squabbler.fname %></td>
        <td><%= squabbler.lname %></td>
        <td><%= squabbler.alias %></td>
        <td><%= squabbler.sole_squabbler %></td>
        <td><%= squabbler.team_squabbler %></td>
        <td><%= squabbler.judge %></td>
        <td><%= squabbler.twitter_handle %></td>
        <td><%= squabbler.facebook %></td>
        <td><%= squabbler.age %></td>
        <td><%= squabbler.country %></td>
        <td><%= squabbler.gender %></td>
        <td><%= link_to 'Show', squabbler, class: "btn btn-link" %></td>
        <td><%= link_to 'Edit', edit_squabbler_path(squabbler), class: "btn btn-link" %></td>
        <td><%= link_to 'Destroy', squabbler, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-link" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Squabbler', new_squabbler_path, class: "btn btn-link"  %>

app/views/squabblers/new.html.erb
<h1>New Squabbler</h1>

<%= render 'form', squabbler: @squabbler %>

<%= link_to 'Back', squabblers_path, class: "btn btn-link"  %>

app/views/squabblers/show.html.erb
<p id="notice"><%= notice %></p>

<div class="row">
  <div class="col-md-4">
    <div class="thumbnail">
    <%= image_tag @squabbler.image.url(:medium) %>
    </div>
    <h3><%= @squabbler.fname %> <%= @squabbler.lname %></h3>
    </div>
  <div class="col-md-4">
    <p>
      <strong>Fname:</strong>
      <%= @squabbler.fname %>
    </p>

    <p>
      <strong>Lname:</strong>
      <%= @squabbler.lname %>
    </p>

    <p>
      <strong>Alias:</strong>
      <%= @squabbler.alias %>
    </p>

    <p>
      <strong>Sole squabbler:</strong>
      <%= @squabbler.sole_squabbler %>
    </p>

    <p>
      <strong>Team squabbler:</strong>
      <%= @squabbler.team_squabbler %>
    </p>

    <p>
      <strong>Judge:</strong>
      <%= @squabbler.judge %>
    </p>

    <p>
      <strong>Twitter handle:</strong>
      <%= @squabbler.twitter_handle %>
    </p>

    <p>
      <strong>Facebook:</strong>
      <%= @squabbler.facebook %>
    </p>

    <p>
      <strong>Age:</strong>
      <%= @squabbler.age %>
    </p>

    <p>
      <strong>Country:</strong>
      <%= @squabbler.country %>
    </p>

    <p>
      <strong>Gender:</strong>
      <%= @squabbler.gender %>
    </p>
  </div>
</div>

<%= link_to 'Edit', edit_squabbler_path(@squabbler), class: "btn btn-link"  %> |
<%= link_to 'Back', squabblers_path, class: "btn btn-link"  %>